### PR TITLE
Fix conversion for a Hash with nil key

### LINKED ISSUE #94: NoMethodError: undefined method `length' for nil when processing malformed query strings
**Current behaviour**
The WAF converter crashes with `NoMethodError: undefined method 'length' for nil` when processing HTTP requests containing malformed query strings like `?&cookie_id=test123`.
```
NoMethodError: undefined method `length' for nil
waf/converter.rb:56:in `block in ruby_to_object': undefined method `length' for nil (NoMethodError)
    from waf/converter.rb:51:in `each'
    from waf/converter.rb:51:in `with_index'
    from waf/converter.rb:51:in `ruby_to_object'
    from waf/context.rb:47:in `run'
    from security_engine/runner.rb:78:in `try_run'
    from security_engine/runner.rb:39:in `run'
    from appsec/context.rb:44:in `run_waf'
    from gateway/watcher.rb:39:in `block in watch_request'
    from gateway/middleware.rb:18:in `call'
```

**Expected behaviour**
The converter should handle `nil` keys gracefully without crashing when processing malformed query parameters.

**Steps to reproduce**
1. Send an HTTP OPTIONS request with a malformed query string: `OPTIONS /v0/feature_toggles?&cookie_id=test123`
2. The WAF converter attempts to process the query parameters
3. The malformed query string results in a hash with a `nil` key
4. The converter calls `.length` on the `nil` key at line 56, causing the crash

Root cause: The issue is in `/lib/datadog/appsec/waf/converter.rb` at line 56:
```ruby
if max_string_length && k.length > max_string_length
```
When processing `?&cookie_id=test`, the query parsing creates hash entries where the key (`k`) can be `nil`.

**How does `libddwaf` help you?**
It is apart of the datadog gem we rely on.

**Environment**
* **libddwaf version:** 1.24.1.1.0
* **libddwaf gem platform:** x86_64-linux
* **Ruby version:** 3.3.6  
* **Ruby platform:** x86_64-linux
* **Operating system:** Linux

**Additional Context**
- **Working version**: libddwaf 1.24.1.0.3 (datadog 2.19.0)
- **Broken version**: libddwaf 1.24.1.1.0 (datadog 2.20.0)
- **Regression introduced by**: Commit [93bc90c](https://github.com/DataDog/libddwaf-rb/commit/93bc90c3143656e1953ebb50c068629efd691418) "Change converter to mark the top object as input truncated" (suspected)

**Suggested fix**: Add nil check before calling `.length`:
```ruby
if max_string_length && k&.length && k.length > max_string_length
```

### PR DESCRIPTION
**Pull request by y9v**
Fixes #94

**What does this PR do?**
It fixes conversion for a Hash that has a `nil` key.

**Motivation**
https://github.com/DataDog/libddwaf-rb/issues/94
https://github.com/DataDog/dd-trace-rb/issues/4885

**Additional Notes**
None.

**How to test the change?**
CI should be enough.

### CODE REVIEW

File: spec/datadog/appsec/waf/converter_spec.rb [hunk 1]
```diff
@@ -303,6 +303,12 @@
             expect(k).to eq "fooooooooo"
             expect(obj).to be_truncated
           end
+
+          it "converts hash with a nil key" do
+            obj = described_class.ruby_to_object({nil => :foo}, max_string_length: max_string_length)
```
Comment (Strech) [inline spec/datadog/appsec/waf/converter_spec.rb:308]: As it belongs to the truncation, could we add check that it will not be marked as truncated?

Additional question, what if the key is not a string? What if it's an object or number? Or how the nil sneak into the conversion?

Comment (y9v) [reply spec/datadog/appsec/waf/converter_spec.rb:308]: good point, the key could be basically anything - and we are converting it to a string later. I think I will move the conversion to happen earlier.

Comment (y9v) [reply spec/datadog/appsec/waf/converter_spec.rb:308]: I also noticed that symbols were incorrectly marked as truncated before: [`2e0c728` (#96)](https://github.com/DataDog/libddwaf-rb/pull/96/commits/2e0c72889a244238615cd745e418e15871815734#diff-b08d628c531f0660b9c26165feef32587e88dbdae2fd4f2409508a1353a07a1fR93-R98)

**Review by Strech — APPROVED** [review]
